# CircleCI パイプライン プロセス エンジンの最新のバージョンである 2.1 を使用します。
# 参照: https://circleci.com/docs/ja/2.0/configuration-reference/
version: 2.1

# Orb(構成パッケージ)を使用します。
orbs:
  # welcome-orb の依存関係を宣言します。
  welcome: circleci/welcome-orb@0.4.1

# ジョブのオーケストレーションまたはスケジュール設定を行います。
workflows:
  # ワークフローに "welcome" と命名します。
  welcome:
    # welcome/run ジョブを専用のコンテナで実行します。
    jobs:
      - welcome/run
