version: 2.1

jobs: # 1回の実行の基本作業単位
  build:  # "workflows" を使用しない実行ではエントリ ポイントとして "build" ジョブが必要です。
    macos:  # macOS Executor の仕様を指定します。
      xcode: 13.0.0
    steps:  # 実行する一連のコマンド
      - checkout  # バージョン管理システムからコードをプルします
      - run:
          # Xcode の CLI ツール "xcodebuild" を使用してテストを実行します。
          name: 単体テストの実行
          command: xcodebuild test -workspace Nasa.xcworkspace -scheme Nasa -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.5'
      - run:
          # アプリケーションをビルドします。
          name: アプリケーションのビルド
          command: xcodebuild -workspace Nasa.xcworkspace -scheme Nasa -allowProvisioningUpdates
